yoroduyaken/blog-crud

- app/Http/Controllers/HomeController.php
- resources/views/home.blade.php
- routes/web.php
#1 
close #1
レビューして欲しい内容
`/home`にてきちんと表示されるかどうか。
> Make home page

- app/Http/Controllers/BlogController.php
- resources/views/blog.blade.php
- routes/web.php
#4 
close#4
レビューして欲しい内容
`/blog`にてブログページが表示されるかどうか。
> Make blog page

- resources/views/home.blade.php
#5
close #5
レビューして欲しい内容
`/home`に作成した「投稿する」リンクが`/blog`へきちんと遷移するかどうか。
> /homeに/blogのページへ遷移するリンクを作成した

- resources/views/top.blade.php
- routes/web.php
#9 
close #9 
レビューして欲しい内容
`/`にてtop ページがきちんと表示されるかどうか。
> topページを作成した。

- app/Http/Controllers/BlogController.php
- app/Models/Blog.php
- database/migrations/2022_12_04_124511_create_blogs_table.php
- resources/views/blog.blade.php
- routes/web.php
#11 
close #11 
レビューして欲しい内容
ブログが投稿出来ているかどうか。
> Make store blog post

- app/Http/Controllers/BlogController.php
- resources/views/blogs.blade.php
- routes/web.php
#12 
close #12 
レビューして欲しい内容
`/blogs`にて投稿一覧が表示されるかどうか。
> Edit blogs index page

- app/Http/Controllers/BlogController.php
- resources/views/edit.blade.php
- routes/web.php
- #15 
close #15 
レビューして欲しい内容
ブログの編集画面が表示されるかどうか。
> Make blog edit page

- app/Http/Controllers/RegisterController.php
- resources/views/register.blade.php
- routes/web.php
- #20 
close #20 
レビューして欲しい内容
`/register`にて登録画面がきちんと表示されるかどうか。
> Make register page

- app/Http/Controllers/RegisterController.php
- routes/web.php
- #19 
close #19
レビューして欲しい内容
きちんと登録されるかどうか。
> Make register function

- app/Http/Controllers/LoginController.php
- resources/views/login.blade.php
- routes/web.php
- #21
close #21 
ログイン画面が表示されるかどうか。
> Make login page

- app/Http/Controllers/LoginController.php
- routes/web.php
- #22 
close #22 
レビューして欲しい内容
きちんとログインできるかどうか。
> Make login auth function

- app/Http/Controllers/BlogController.php
- app/Models/Blog.php
- resources/views/blog.blade.php
- resources/views/edit.blade.php
- resources/views/show.blade.php
- #24 
close #24 
レビューして欲しい内容
ログインしているユーザーにて編集と削除ができるかどうか。
> Make auth edit and delete function

- resources/views/show.blade.php
- #25 
close #25 
レビューして欲しい内容
編集ボタンと削除ボタンが機能するかどうか
> 編集ボタンを追加し削除ボタンの名前を修正した

- app/Http/Controllers/LoginController.php
- resources/views/home.blade.php
- routes/web.php
- #26 
close #26 
レビューして欲しい内容
ユーザーが`/`にログアウトされるかどうか
> Make logout function

- resources/views/home.blade.php
- resources/views/top.blade.php
- #27 
close #27 
レビューして欲しい内容
諸々のボタンを押した時に画面が正しく遷移されるかどうか。
> Make four buttons

- database/seeders/DatabaseSeeder.php
- database/seeders/UsersTableSeeder.php
> seederのユーザーを追加した。

- database/seeders/BlogsTableSeeder.php
- database/seeders/DatabaseSeeder.php
#29 
close #29 
レビューして欲しい内容
BlogsTableSeederが追加されているかどうか。
> BlogsTableSeederを追加した。

- database/factories/UserFactory.php
- database/seeders/UsersTableSeeder.php
#30 
close #30 
レビューして欲しい内容
Factoryにてユーザーを10人作成した。
> Factoryにてユーザーを10人作成した。

- app/Http/Controllers/RegisterController.php
#47 
close #47 
レビューして欲しい内容
登録と同時にログインできるかどうか。
> 登録と同時にログイン出来るようにした。

- app/Http/Controllers/BlogController.php
- app/Http/Controllers/LoginController.php
- app/Http/Controllers/RegisterController.php
- app/Models/User.php
- routes/web.php
#31 
close #31 
レビューして欲しい内容
登録後に登録者へ向けてメール確認がされるかどうか。
> Mail verification function
